apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argo-update
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: argo-update
          labels:
            tier: api
        spec:
          volumes:
            - name: logs
              persistentVolumeClaim:
                claimName: datacron-logs
          containers:
            - name: argo-update
              image: argovis/datacron:0.4.0
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "0Gi"
                  cpu: "0m"
                limits:
                  memory: "2Gi"
                  cpu: "750m"
              volumeMounts:
                - mountPath: "/usr/src/argo-database/logs"
                  name: logs
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000660000
            runAsGroup: 1000660000
